### ISSUE TITLE
Synthesis of AIB

### ISSUE THREAD

**Issue by rahulrvm82** [chipsalliance/aib-phy-hardware#9] opened 2020-02-12 10:25 UTC
Hello All,

If anyone had tried to synthesis of the code,please provide details of constraint.

Thanks 
Rahul 
(rahul_rvm82@yahoo.co.in)

**Comment by dkehlet** [comment] 2020-02-24 23:45
Duplicate of issue #4.  Rahul, please watch that issue.

**Closed as completed** 2020-02-24 23:44 UTC
